---
kind: pipeline
type: docker
name: default


platform:
  os: linux
  arch: arm64

node:
  runner: drone-runner-1

steps:
  - name: greeting
    commands:
      - echo hello world
trigger:
  event:
    exclude:
      - pull_request
